[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000193DA329910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d67d2ed0-6fe5-4592-89dd-be658da00641
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000193DA2DECF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d67d2ed0-6fe5-4592-89dd-be658da00641
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000193DA32A090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d67d2ed0-6fe5-4592-89dd-be658da00641