{"name": "Login Succesfully -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 26, in step_impl\n    context.driver.isUserLoggedIn()\n  File \"C:\\Users\\sebas\\OneDrive\\Desktop\\Inlaze - automation\\scripts\\global_scripts.py\", line 238, in isUserLoggedIn\n    WebDriverWait(self.driver, 10).until(\n  File \"C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user is on the web page", "status": "passed", "attachments": [{"name": "open_web_driver", "source": "88af25b9-0faf-4e5b-86b6-2d8397c89943-attachment.png", "type": "image/png"}], "start": 1722731702097, "stop": 1722731708672}, {"name": "When the user put the login details like: inlaze-user@yopmail.com, T123@mails", "status": "passed", "start": 1722731708672, "stop": 1722731708719}, {"name": "And the user select the \"Sign In\" button", "status": "passed", "attachments": [{"name": "select_login_button", "source": "7379fe74-af26-498a-908a-6942dbd5b1ff-attachment.png", "type": "image/png"}], "start": 1722731708719, "stop": 1722731708977}, {"name": "Then the user is logged into the aplication", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 26, in step_impl\n    context.driver.isUserLoggedIn()\n  File \"C:\\Users\\sebas\\OneDrive\\Desktop\\Inlaze - automation\\scripts\\global_scripts.py\", line 238, in isUserLoggedIn\n    WebDriverWait(self.driver, 10).until(\n  File \"C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1722731708977, "stop": 1722731721575}], "parameters": [{"name": "email", "value": "inlaze-user@yopmail.com"}, {"name": "password", "value": "T123@mails"}], "start": 1722731702096, "stop": 1722731721577, "uuid": "b77316bb-eb95-4a52-8b11-d5797a0f4eba", "historyId": "7d56b6b50a21c68d17124e8cd41475cc", "fullName": "Login Succesfully: Login Succesfully", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login Succesfully"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}